baseURL = "https://112revelats.112books.eu/"
title = "112 Revelats"
defaultContentLanguage = "ca"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "term"]

[languages]
  [languages.ca]
    languageName = "CA"
    weight = 1
    disableKinds = ["taxonomy", "term"]

  [languages.es]
    languageName = "ES"
    weight = 2
    disableKinds = ["taxonomy", "term"]

  [languages.en]
    languageName = "EN"
    weight = 3
    disableKinds = ["taxonomy", "term"]

[params]
  description = "Projecte de fotollibres col·lectius"
  author = "112Books"
  instagram = "https://www.instagram.com/112books.eu/"
  facebook = "https://www.facebook.com/112books/"
  llibreUrl = "https://www.112books.eu/producte/arrencant-el-dia-112-revelats/"
  ogImage = "/img/hero-bg.png"
  pressDossier = "/pdf/dossier-premsa-112-revelats.pdf"
  goatcounter = "112revelats"
  formAction = "https://formspree.io/f/maqzqynz"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML"]

[build]
  writeStats = false
